/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ServicesTechnicTvVistas;
import ServicesTechnicTves.Dao.TecnicoDao;
import javax.swing.JOptionPane;
import ServicesTechnicTves.Model.Entidades.Tecnico;
import ServicesTechnicTvVistas.PrincipalForm;

/**
 *
 * @author escam
 */
public class GestionTecnico extends javax.swing.JInternalFrame {

   
    public GestionTecnico() {
        initComponents();
        inabilitar();
        
    }
    



    public void inabilitar(){
        campoNombreTecnico.setEnabled(false);
        campoApellidoTecnico.setEnabled(false);
        campoIdentificacionTecnico.setEnabled(false);
        campoEspecialidadTecnico.setEnabled(false);
        botonRegistrar.setText("Nuevo");
        botonModificar.setEnabled(false);
        botonCancelarCliente.setEnabled(false);
        limpiar();
    }
    
    public void habilitar(){
        campoNombreTecnico.setEnabled(true);
        campoApellidoTecnico.setEnabled(true);
        campoIdentificacionTecnico.setEnabled(true);
        campoEspecialidadTecnico.setEnabled(true);
        botonRegistrar.setText("Registrar");
        
    
    }
    
        public void limpiar(){
        campoNombreTecnico.setText("");
        campoApellidoTecnico.setText("");
        campoIdentificacionTecnico.setText("");
        campoEspecialidadTecnico.setText("");
        
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIdentificacionTecnico = new javax.swing.JLabel();
        lblNombreTecnico = new javax.swing.JLabel();
        lblApellidoTecnico = new javax.swing.JLabel();
        lblEspecialidadTecnico = new javax.swing.JLabel();
        campoNombreTecnico = new javax.swing.JTextField();
        campoApellidoTecnico = new javax.swing.JTextField();
        campoIdentificacionTecnico = new javax.swing.JTextField();
        campoEspecialidadTecnico = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonCancelarCliente = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();
        botonBuscarTecnico = new javax.swing.JButton();
        botonLimpiarTecnico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTecnico = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Formulario de Gestión de Tecnicos");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DASDASD.png"))); // NOI18N

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(189, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Tecnicos"));

        lblIdentificacionTecnico.setText("IDENTIFICACIÓN");

        lblNombreTecnico.setText("NOMBRE");

        lblApellidoTecnico.setText("APELLIDO");

        lblEspecialidadTecnico.setText("ESPECIALIDAD");

        campoNombreTecnico.setForeground(new java.awt.Color(204, 204, 204));
        campoNombreTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreTecnicoActionPerformed(evt);
            }
        });

        campoApellidoTecnico.setForeground(new java.awt.Color(204, 204, 204));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");

        botonCancelarCliente.setText("Cancelar");

        botonEliminarCliente.setText("Eliminar");
        botonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarClienteActionPerformed(evt);
            }
        });

        botonBuscarTecnico.setText("Buscar");
        botonBuscarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTecnicoActionPerformed(evt);
            }
        });

        botonLimpiarTecnico.setText("Limpiar");
        botonLimpiarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarTecnicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidoTecnico)
                            .addComponent(lblNombreTecnico)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdentificacionTecnico, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEspecialidadTecnico)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoApellidoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoEspecialidadTecnico)
                                .addComponent(campoIdentificacionTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonLimpiarTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(botonCancelarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(botonBuscarTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonRegistrar)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarCliente)
                        .addGap(19, 19, 19)
                        .addComponent(botonCancelarCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreTecnico)
                            .addComponent(campoNombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoApellidoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoTecnico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoIdentificacionTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdentificacionTecnico))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEspecialidadTecnico)
                            .addComponent(campoEspecialidadTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarTecnico)
                    .addComponent(botonLimpiarTecnico))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tablaTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTecnico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreTecnicoActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

            if(botonRegistrar.getText().equals("Nuevo")){
            
            habilitar();
            }else{
                try {
            String nombre = campoNombreTecnico.getText();
            String apellido = campoApellidoTecnico.getText();
            String identificacion = campoIdentificacionTecnico.getText();
            String especialidad = campoEspecialidadTecnico.getText();
            

            if (nombre == null || nombre.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre es requerido");
                return;
            }

            if (apellido == null || apellido.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El apellido es requerido");
                return;
            }
            
            if (identificacion == null || identificacion.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La identificacion es requerida");
                return;
            }
    
            if (especialidad == null || especialidad.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El numero de telefono es requerido");
                return;
            }
            
            

            var tecnico = new Tecnico(nombre,  apellido, identificacion, especialidad);
            var usuarioDao = new TecnicoDao();
            usuarioDao.registrar(tecnico);
            JOptionPane.showMessageDialog(this, "Tecnico guardado con exito");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
            
        }
             

        
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarClienteActionPerformed
       String identificacion = campoIdentificacionTecnico.getText().trim();

    if (identificacion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese la identificacion del técnico a eliminar.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este técnico?", "Confirmar", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        TecnicoDao tecnicoDao = new TecnicoDao();
        boolean eliminado = tecnicoDao.eliminarTecnico(identificacion);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Técnico eliminado correctamente.");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un técnico con esa identificacion.");
        }
    }
    }//GEN-LAST:event_botonEliminarClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new PrincipalForm().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonBuscarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTecnicoActionPerformed
        try {
            var identificacion = campoIdentificacionTecnico.getText();
            if (identificacion == null || identificacion.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La identificacion es requerido para buscar");
                return;
            }
            var tecnicoDao = new TecnicoDao();
            var tecnico = tecnicoDao.buscarPorId(identificacion);

            campoNombreTecnico.setText(tecnico.getNombre());
            campoApellidoTecnico.setText(tecnico.getApellido());
            campoIdentificacionTecnico.setText(tecnico.getIdentificacion());
            campoEspecialidadTecnico.setText (tecnico.getEspecialidad());
        } catch (Exception ex) {
              JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonBuscarTecnicoActionPerformed

    private void botonLimpiarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarTecnicoActionPerformed
        limpiar();
    }//GEN-LAST:event_botonLimpiarTecnicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarTecnico;
    private javax.swing.JButton botonCancelarCliente;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonLimpiarTecnico;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoApellidoTecnico;
    private javax.swing.JTextField campoEspecialidadTecnico;
    private javax.swing.JTextField campoIdentificacionTecnico;
    private javax.swing.JTextField campoNombreTecnico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoTecnico;
    private javax.swing.JLabel lblEspecialidadTecnico;
    private javax.swing.JLabel lblIdentificacionTecnico;
    private javax.swing.JLabel lblNombreTecnico;
    public javax.swing.JTable tablaTecnico;
    // End of variables declaration//GEN-END:variables

    private void setNombre(String trim) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
