package ServicesTechnicTvVistas;
import javax.swing.JOptionPane;
import ServicesTechnicTvVistas.Formu;
import ServicesTechnicTvVistas.GestionTecnico;
import ServicesTechnicTvVistas.GestionCliente;
import ServicesTechnicTvVistas.GestionMantenimiento;
import ServicesTechnicTvVistas.GestionDispositivo;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */

/**
 *
 * @author escam
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioPr = new javax.swing.JDesktopPane();
        titulo = new javax.swing.JLabel();
        botonGestionarTecnico = new javax.swing.JButton();
        SalirdelMenuGestionar = new javax.swing.JButton();
        botonGestionarCliente = new javax.swing.JButton();
        botonGestionarDispositivo = new javax.swing.JButton();
        botonGestionarMantenimiento = new javax.swing.JButton();
        iconlogo = new javax.swing.JLabel();
        tituloservice = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        menuGestorUsuario = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        titulo.setText("SISTEMA DE REPARACIONES");
        escritorioPr.add(titulo);
        titulo.setBounds(200, 190, 280, 43);

        botonGestionarTecnico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGestionarTecnico.setText("Gestor de Tecnicos");
        botonGestionarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarTecnicoActionPerformed(evt);
            }
        });
        escritorioPr.add(botonGestionarTecnico);
        botonGestionarTecnico.setBounds(160, 260, 340, 30);

        SalirdelMenuGestionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SalirdelMenuGestionar.setText("Salir");
        SalirdelMenuGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirdelMenuGestionarActionPerformed(evt);
            }
        });
        escritorioPr.add(SalirdelMenuGestionar);
        SalirdelMenuGestionar.setBounds(160, 420, 340, 30);

        botonGestionarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGestionarCliente.setText("Gestor de Clientes");
        botonGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarClienteActionPerformed(evt);
            }
        });
        escritorioPr.add(botonGestionarCliente);
        botonGestionarCliente.setBounds(160, 300, 340, 30);

        botonGestionarDispositivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGestionarDispositivo.setText("Gestor de Dispositivos");
        botonGestionarDispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarDispositivoActionPerformed(evt);
            }
        });
        escritorioPr.add(botonGestionarDispositivo);
        botonGestionarDispositivo.setBounds(160, 340, 340, 30);

        botonGestionarMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGestionarMantenimiento.setText("Gestor de Mantenimiento");
        botonGestionarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarMantenimientoActionPerformed(evt);
            }
        });
        escritorioPr.add(botonGestionarMantenimiento);
        botonGestionarMantenimiento.setBounds(160, 380, 340, 30);

        iconlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DASDASD.png"))); // NOI18N
        escritorioPr.add(iconlogo);
        iconlogo.setBounds(680, 280, 130, 120);

        tituloservice.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        tituloservice.setText("SERVICE TECHNIC REPAIR");
        escritorioPr.add(tituloservice);
        tituloservice.setBounds(90, 110, 510, 60);

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/32w.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favi1.png"))); // NOI18N
        editMenu.setMnemonic('e');

        menuGestorUsuario.setMnemonic('t');
        menuGestorUsuario.setText("Gestor de Usuarios");
        menuGestorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestorUsuarioActionPerformed(evt);
            }
        });
        editMenu.add(menuGestorUsuario);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/32x.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        menuBar.add(helpMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/32r.png"))); // NOI18N
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPr, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPr, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGestorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestorUsuarioActionPerformed
        Formu ventana = new Formu();
        escritorioPr.add(ventana);
        ventana.show();
    }//GEN-LAST:event_menuGestorUsuarioActionPerformed

    private void botonGestionarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarTecnicoActionPerformed
        GestionTecnico ventana = new GestionTecnico();
        escritorioPr.add(ventana);
        ventana.show();
    }//GEN-LAST:event_botonGestionarTecnicoActionPerformed

    private void SalirdelMenuGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirdelMenuGestionarActionPerformed
    System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_SalirdelMenuGestionarActionPerformed

    private void botonGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarClienteActionPerformed
        GestionCliente ventana = new GestionCliente();
        escritorioPr.add(ventana);
        ventana.show();
    }//GEN-LAST:event_botonGestionarClienteActionPerformed

    private void botonGestionarDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarDispositivoActionPerformed
        GestionDispositivo ventana = new GestionDispositivo();
        escritorioPr.add(ventana);
        ventana.show();
    }//GEN-LAST:event_botonGestionarDispositivoActionPerformed

    private void botonGestionarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarMantenimientoActionPerformed
        GestionMantenimiento ventana = new GestionMantenimiento();
        escritorioPr.add(ventana);
        ventana.show();
    }//GEN-LAST:event_botonGestionarMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main (String args[]){
/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirdelMenuGestionar;
    private javax.swing.JButton botonGestionarCliente;
    private javax.swing.JButton botonGestionarDispositivo;
    private javax.swing.JButton botonGestionarMantenimiento;
    private javax.swing.JButton botonGestionarTecnico;
    private javax.swing.JMenu editMenu;
    public javax.swing.JDesktopPane escritorioPr;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel iconlogo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuGestorUsuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloservice;
    // End of variables declaration//GEN-END:variables

}
